src/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),

]

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
    url(r'^me/add$', views.post_new, name='post_new_product'),
   	
   	url(r'^profile/(?P<slug>[\w+^\s]+)/$', views.UserProfileView.as_view(), name='profile_view'), 
   	url(r'^profile/id/(?P<pk>\d+)/$', views.UserProfileView.as_view()),
]

src/socialhand/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import shop.urls
from search import views as search_views
from . import views, ocv
# from .views import notes
from django.views.generic import TemplateView



urlpatterns =  [
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include(shop.urls, namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'^search/', views.notes, name='search'),
    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL for social Auth
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^contact/$',views.contact, name='contact'),
    url(r'^api/',include('socialhand.api.urls',namespace='api')),
    #testing opencv tools into AR
    url(r'^face_detection/camera/$', ocv.camera),
    url(r'^silver_ar/$',views.three.as_view(), name='three'),
    url(r'^honeywell/$',views.Cascade.as_view(), name='cascade'),
    # testing object detect js
    url(r'^glasses/$',views.ben_frank.as_view(), name='ben_frank'),
    url(r'^g876_id0/$',views.ben_frank.as_view(), name='ben_frank'),

    #testing 360 look around  virtual tour with three.js
    url(r'^virtual/$', views.LookAround_360.as_view(), name = 'look_around' ),

     #testing babylon.js
    url(r'^virtual_test_kitchen/$', views.VirtualBabylon.as_view(), name = 'virtual_reality' ),
    url(r'^ar_cr3/$', views.Cr3ationAR.as_view(), name = 'AR_creation' ),
    url(r'^camaro/$', views.CamaroVirtual.as_view(), name = 'camaro' ),
    url(r'^warehouse_test/$', views.Warehouse.as_view(), name = 'warehouse' ),


]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
from django.db import models
from django.conf import settings
from django.utils import timezone

from embed_video.fields import EmbedVideoField
from django.core.urlresolvers import reverse
from django.core.validators import URLValidator
from django.utils.translation import gettext_lazy as _
  
 

class BaseProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True)
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    market = models.CharField(_('Market'), max_length=30, blank=True)
    picture = models.ImageField(_('Profile picture'),
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    background_1 = models.ImageField(_('background_1'),
                                    upload_to = 'profile_background/%Y-%m-%d',
                                    null = True,
                                    blank = True,)
    background_2 = models.ImageField(_('background_2'),
                                    upload_to = 'profile_background/%Y-%m-%d',
                                    null = True,
                                    blank = True,)
    background_3 = models.ImageField(_('background_3'),
                                    upload_to = 'profile_background/%Y-%m-%d',
                                    null = True,
                                    blank = True,)
    fb_link = models.URLField(_('facebook'),
                            validators =[URLValidator()],
                            null=True,
                            blank=True,)
    tw_link = models.URLField(_('Twitter'),
                            validators = [URLValidator()],
                            null=True,
                            blank=True,)
    insta_link=models.URLField(_('instagram'),
                            validators=[URLValidator()],
                            null=True,
                            blank=True,)

    bio = models.CharField(_('Our history'), max_length=400, blank=True, null=True,
        help_text=("Relata un poco sobre tu trabajo: cuánto tiempo llevas haciéndolo, cómo empezó, dónde nació tu creatividad, etc"))

    email_verified = models.BooleanField("Email verificado", default=False)

    class Meta:
        abstract = True

    def get_short_name(self):
        "Devuleve el nombre de la tienda"
        return self.market

@python_2_unicode_compatible
class Profile(BaseProfile):
    def __str__(self):
        return "{}' Tienda". format(self.user)


#creating post model for entries.

class Post(models.Model):
    author = models.ForeignKey('authtools.User')
    title = models.CharField(max_length=400)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    


    def published(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Video(models.Model):
    author= models.ForeignKey('authtools.User')
    title = models.CharField(_('Title'),max_length=200)
    video = EmbedVideoField(
                            help_text='add a valid URL',
                            null=True,
                            blank=True)
    class Meta: 
        ordering = ('title',)
        verbose_name = 'video'
        verbose_name_plural = 'videos'


    def __unicode__(self):
        return self.title


    # def get_absolute_url(self):
    #         return reverse('profiles:detail', kwargs={'pk': self.pk})

        

src/profiles/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model
from . import models
from .models import Post
from shop.models import Category, Product

 
#define user parameter register_registration

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name'),
            )

    class Meta:
        model = User
        fields = ['name']


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('market'),
            Field('bio'),
            Field('picture'),
            HTML(""" <hr class="basic-custom">"""),
            Field('background_1'),
            HTML("""{% if user.profile.background_1 %}
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{ user.profile.background_1 }}">                
                    {% endif %}
                    <hr class="custom">""", ),                    
            Field('background_2'),
            HTML("""{% if user.profile.background_2 %}
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{ user.profile.background_2 }}">
                    {% endif %}
                    <hr class="custom">""", ),
            Field('background_3'),   
            HTML("""{% if user.profile.background_3 %}
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{ user.profile.background_3 }}">
                    {% endif %}
                    <hr class="custom">""", ),
            Field('fb_link'),
            Field('tw_link'),
            Field('insta_link'),

            Submit('update', 'Update', css_class="btn-success"),
            )

    class Meta:
        model = models.Profile
        fields = ['picture', 'bio', 'market','background_1','background_2','background_3','fb_link','tw_link','insta_link',]    


# form for add a new product 
class ShopFor(forms.ModelForm):


    def __init__(self, *args, **kwargs):
        super(ShopFor, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('category'),
            Field('name'),
            Field('slug'),
            Field('image'),
            Field('description'),
            Field('price'),
            Field('stock'),
            Field('available'),
            Submit('update', 'Update', css_class="btn-success"),
            )


    class Meta:
        model = Product
        fields =['name','slug', 'category', 'image', 'description', 'price','stock', ]


# postform fue agregado para auxiliar la creacion de shopfor 
class PostForm(forms.ModelForm):

        class Meta:
            model = Post
            fields = ('title','text','author',)

src/profiles/views.py
from __future__ import unicode_literals
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from braces.views import LoginRequiredMixin
from django.contrib.auth.mixins import AccessMixin
from . import forms
from . import models
from django.http import HttpResponse
 
from django.utils import timezone
from django.shortcuts import render
from .models import Post, Video
from .forms import ShopFor, PostForm
import shop.models  
from shop.models import Product
from django.contrib.auth.decorators import login_required
from authtools.models import User 
from django.views.generic import ListView, DetailView
from .models import Video
  
class ShowProfile(AccessMixin,TemplateView):
    template_name = "profiles/show_profile.html"  
    http_method_names = ['get', 'post' ]
    def get(self, request, *args, **kwargs):
        # name=self.kwargs.get('name')
        # u = get_object_or_404(User,name=name)
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            #add anonymoues user?
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        # print products by profile kwargs returns a dictionary
        products = Product.objects.filter(author=user).order_by('?')
        videos = Video.objects.filter(author=user)
        kwargs['products']= products
        kwargs['videos']=videos
        return super(ShowProfile, self).get(request, *args, **kwargs)
    

    # show us all products in ShowProfile
    # def get_context_data(self,**kwargs):
    #     context = super(ShowProfile, self).get_context_data(**kwargs)
    #     context['products'] =Product.objects.filter(available=True)
    #     return  context

class UserProfileView(DetailView):
    model = User
    slug_field = "name"
    template_name = "profiles/show_profile.html"

class EditProfile(LoginRequiredMixin,TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "saved details")
        return redirect("profiles:show_self")




#Add new product for sell
def post_new(request):
        if request.method == "POST":
            form = ShopFor(request.POST,
                         request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.published_date = timezone.now()
                post.save()
                return redirect("profiles:show_self")
        else:
            form = ShopFor()
        return render(request, 'profiles/product_add.html', {'form': form})



# def post_new(request):
#         if request.method == "POST":
#             form = PostForm(request.POST)
#             if form.is_valid():
                
#                 post = form.save(commit=False)
#                 post.author = request.user
#                 post.published_date = timezone.now()
#                 post.save()
#                 return redirect('/')
#         else:
#             form = PostForm()
#         return render(request, 'profiles/product_add.html', {'form': form})


class PostVideo(ListView):
    model = Video

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div class="container">
  <h1 class="text-primary">Editar Perfil</h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>Personal info</h3>
      <form enctype="multipart/form-data" method="post">
	{% crispy user_form %}
	{% crispy profile_form %}

  {{user.profile.background_1}}
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-primary pull-right" href="{% url 'accounts:password-change' %}">Change Password</a>
    </div>
  </div>
</div>
{% endblock %}

src/profiles/templates/profiles/list_index.html
{% extends 'base.html' %}
 
{% static %}
 
{% block style_css_js %}
//Acá pueden ir los archivos css o js que necesitemos
{% endblock %}
 
{% block contenido_post %}
     
    <h4>Posts</h4>
 
    <div id="data-template" class="endless_page_template">
        {% include "app/archivo.html" %}
    </div>
 
    {% block js %}
        <script src="{% static 'jquery/endless/endless-pagination.js' %}"></script>
        <script>$.endlessPaginate({paginateOnScroll: true});</script>
    {% endblock %}
 
{% endblock %}

src/profiles/templates/profiles/post_list.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}

src/profiles/templates/profiles/product_add.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Nuevo producto{% endblock %}

{% block container %}
<body background= "{% static 'image/noimage.png' %}"  ></body>

<div class="container-fluid">
	<div class="row row-centered">
	<div class="col-md-4 col-md-offset-4">
        <br><br>
        <h2>Añadir nuevo producto</h2>

        <form enctype="multipart/form-data" method="post">
			{% crispy form %}
			{{ csrf_token }}
		</form>

    </div>
    </div>
</div>
    {% endblock %}


{% block scripts %}
<script src="{% static 'site/js/dropzone.js' %}"> </script>

</script>



{% endblock scripts %}

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block title %}{{ block.super }}{{ show_user.profile.get_short_name }}{% endblock %}

{% block container %}
<div id="fb-root"></div>


<!--======== Text over fullscreen carousel ===================-->
<div class="overlay">
  <div class=" col-md-12 text-center">
    <!--<h1><font color="white">Qué es lo que trabajas?</font></h1>-->
    <!--<h3>descripcion</h3>-->
      {% if editable %}
          <div class="col-md-12">
            <a href="{% url 'profiles:edit_self' %}" class="btn btn-default">Editar Perfil</a>
          </div>
      {% endif %}
  </div><!-- /col-md-12 text-center -->
    <div class="container-fluid">
      <div  class="col-xs-6 col-md-2">
        <div id="container-fluid">
        <h1 style="font-family:Lobster;" ><font color="white">{{ show_user.profile.get_short_name }}</font></h1>
        <img title="profile picture" class="img-circle img-responsive img-thumbnail" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 150x150 crop %}">
        </div>
      </div>
    </div>
</div>  <!-- /overlay -->

<!--======== fullscreen carousel =========-->
<div id="carousel">
    <div id="myCarousel" class="carousel fade-carousel slide"  data-ride="carousel" data-interval="5000" data-pause="click">
      <ol class="carousel-indicators">
      {% if  show_user.profile.background_1%}
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      {% else %}
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      {% endif %}
      {% if  show_user.profile.background_2%}
          <li data-target="#myCarousel" data-slide-to="1"></li>
      {% endif %}
      {% if  show_user.profile.background_3%}
          <li data-target="#myCarousel" data-slide-to="2"></li>
      {% endif %}
      </ol>
    <div class="carousel-inner">
    {% if  show_user.profile.background_1%}
        <div class="item slides active">
          <div class="slide-1" style="background-image: url({{ MEDIA_URL }}{{show_user.profile.background_1}});">
          </div>
        </div>
    {% else %}
        <div class="item slides active">
          <div class="slide-1" style="background-image: url({{ MEDIA_URL }}{{"profile_background/wood.jpg"}});">
          </div>
        </div>
    {% endif %}
    {% if  show_user.profile.background_2%}
        <div class="item slides">
          <div class="slide-2" style="background-image: url({{ MEDIA_URL }}{{show_user.profile.background_2}});">
          </div>
        </div>
    {% endif %}
    {% if  show_user.profile.background_3%}
        <div class="item slides">
          <div class="slide-3" style="background-image: url({{ MEDIA_URL }}{{show_user.profile.background_3}});">
          </div>
        </div>
    {% endif %}
    </div>
        <!-- <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a> -->
    </div>
</div>


{% if editable %}
  <hr class="custom">
    <div class="container fluid">
      <div class="col-md-6">
        <a href="{% url 'profiles:post_new_product' %}" class="btn btn-primary">Nuevo Producto</a>
      </div>
    </div>
{% endif  %}
<hr class="custom">
  <div class="container-fluid ">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">
        <h4>{{ show_user.profile.get_short_name }}</h4>
        </li>
        <li class="list-group-item text-right">
          <span class="pull-left">
            <strong style="font-family:Lobster;">Email:</strong>
          </span>
          {{ show_user.email|default:"missing" }}
          {% if editable %}
            {% if show_user.profile.email_verified %}
              <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="Correo electrónico verificado"></span>
              <span class="sr-only">Verificado</span>
            {% else %}
              <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="Correo electrónico No verificado"></span>
              <span class="sr-only">No Verificado</span>
            {% endif %}
        </li>
        <li class="list-group-item text-right">
            <span class="pull-left"><strong style="font-family: Lobster;">Registrado desde:</strong></span>
            {{ show_user.date_joined }}
        </li>
        <li class="list-group-item text-right">
            <span class="pull-left"><strong style="font-family: Lobster;">Ultimo ingreso:</strong></span>
            {{ show_user.last_login }}
        </li>
        {% endif %}
          <li class="list-group-item text-left">
            <ul class="social-network social-circle">
              {% if show_user.profile.fb_link %}
                <li><a href="{{show_user.profile.fb_link}}" class="icoFacebook ico-background" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
              {% endif %}
              {% if sohw_user.profile.tw_link %}
                <li><a href="{{show_user.profile.tw_link}}" class="icoTwitter ico-background" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
              {% endif %}
              {% if show_user.profile.insta_link %}
                <li><a href="{{show_user.profile.insta_link}}" class="icoInstagram ico-background" title="Instagram" target="_blank"><i class="fa fa-instagram"></i></a></li>
              {% endif %}

            </ul>
          </li>
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading" style="font-family: Lobster; font-size:25px; color: white;">{{ show_user.get_full_name }}'s Artesanías
           {% if show_user.profile.slug %}
             <a href="{% url 'profiles:show' show_user.profile.slug %}">
             <span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
             <!--//<span class="sr-only">Ver como</span></a> {{show_user.profile.get_absolute_url}}--> </a>
             <!--{{show_user.profile.slug}}-->
           {% else %}
             <a href="https://github.com/arocks/edge/issues/40" target="_blank"><span>No permalink. See this issue.</span></a>
           {% endif %}
        </div>
        <div class="panel-body">
            <p><strong style="font-size: 20px">Acerca de:</strong> <ul align="left"> {{ show_user.profile.bio }}</ul></p>
        </div>
      </div>
    </div>

    <!--<a href="{% url 'shop:product_list' %}"> visitanos</a>-->
  </div>

<!-- contact social network -->
    <!--<div class="col-md-4 col-md-offset-4">-->
    <!--  <ul class="social-network social-circle">    {% if show_user.profile.fb_link %}-->
    <!--      <li><a href="{{show_user.profile.fb_link}}" class="icoFacebook ico-background" title="Facebook"><i class="fa fa-facebook"></i></a></li>-->
    <!--      {% endif %}-->
    <!--      {% if sohw_user.profile.tw_link %}-->
    <!--      <li><a href="{{show_user.profile.tw_link}}" class="icoTwitter ico-background" title="Twitter"><i class="fa fa-twitter"></i></a></li>-->
    <!--      {% endif %}-->
    <!--      {% if show_user.profile.insta_link %}-->
    <!--      <li><a href="{{show_user.profile.insta_link}}" class="icoInstagram ico-background" title="Instagram"><i class="fa fa-google-plus"></i></a></li>-->
    <!--      {% endif %}-->

    <!--  </ul>-->
    <!--</div>-->

<!-- =========== Embedded Videos ================= -->
<hr class="custom">
<!--<div class="container-fluid">-->
<!--  <div class="video-shared"> -->
<!--    <iframe src="https://player.vimeo.com/video/32761077" width="440" height="240"-->
<!--     frameborder="0" title="Jewelry Design Workshop" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>-->
<!--  </div>-->
<!--</div>-->

<div class="container-fluid">
  <button class="btn btn-warning btn-lg btn-block" type="button" data-toggle="collapse" data-target="#collapse-video" aria-expanded="false" aria-controls="collapseExample">Video gallery</button>
    <div class="collapse" id="collapse-video" >
      <div class=" video-shared ">
        {% for video in videos %}
         {% video video.video '440x240' %}
          {% video video.video as video %}
           <td><a href="{{ video.url }}">{{ video.title }} </a></td>
          {% endvideo %}
        {% endfor %}
      </div>
    </div>
</div>
<!--testing social networks for each user-->
<!--<div class="container-fluid">-->
<!--  <div class="fb-comments" data-href="https://kaayi.pythonanywhere.com//users/show_user-profile-slug" data-width="500PX" data-numposts="3"></div>-->
<!--</div>-->


 <hr class="custom">
 <div id="simple"class="justified-gallery" style="background-color: black" >

{% for product in products %}
  <a href="{{ product.get_absolute_url }}"class="portfolio-box image-frame ">

      <img title="our product" src="{% if product.image %}{% thumbnail product.image 650x650 crop %}{%else %}{% static 'image/noimage.png' %}{% endif %}">
    <div class="portfolio-box-caption">
      <div class="portfolio-box-caption-content">
        <div class="project-category text-faded">
        {{ product.name }}
        </div>
        <div class="project-name">
        <h3>by:{{ show_user.get_full_name }} {{product.id}}</h3>
        </div>
      </div>
    </div>
  </a>
{% endfor %}
  </div>







<!-- </div> -->

{% endblock container %}

{% block scripts %}
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.8&appId=657778311046259";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script src="{% static 'site/js/site.js' %}"></script>
<!-- add scripts for animate scrolling -->
<script src="{% static 'site/js/scrolling-nav.js' %}"></script>
<script src="{% static 'site/js/jquery.easing.min.js' %}"></script>

<script src = "{%static 'site/js/jquery.justifiedGallery.js' %}"></script>
<script>
    $("#simple").justifiedGallery({
    rowHeight : 220,
    lastRow : 'nojustify',
    margins : 15
    });
</script>
<script >
  var back = ["#DF01D7","#8E44AD","#AEA8D3","#F62459","#DB0A5B","#D64541","#D2527F","#522770","#61AEFF","#EBABD6","#543BC4","#ff21e9","#F88400","#FFDA00","#BF4B9C"];
  $('.portfolio-box-caption').each(function() {
    // First random color
    var rand1 = back[Math.floor(Math.random() * back.length)];
    // Second random color
    var rand2 = back[Math.floor(Math.random() * back.length)];
    var grad = $(this);
    // Convert Hex color to RGB
    function convertHex(hex,opacity){
        hex = hex.replace('#','');
        r = parseInt(hex.substring(0,2), 16);
        g = parseInt(hex.substring(2,4), 16);
        b = parseInt(hex.substring(4,6), 16);
      // Add Opacity to RGB to obtain RGBA
        result = 'rgba('+r+','+g+','+b+','+opacity/70+')';
        return result;
    }
    // Gradient rules
    grad.css('background-color', convertHex(rand1,40) );
    grad.css("filter", "progid:DXImageTransform.Microsoft.gradient( startColorstr='"+ convertHex(rand1,40) +"', endColorstr='"+ convertHex(rand2,40) +"',GradientType=0 )");
  })
</script>


{% endblock scripts %}