src/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),

]

src/shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import  ProductListView

urlpatterns = [

	url(r'^productos/$', ProductListView.as_view(), name='product_list'),
	url(r'^productos/(?P<slug>[-\w]+)/$',ProductListView.as_view(),name='product_list_by_category'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/edit/$', views.product_edit, name='product_edit'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/remove/$',views.product_remove, name='product_remove'),
	url(r'^ranking/$', views.product_ranking, name='create'),

    #render 3d model for custom code for each model
	url(r'^productos/render/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.Rendering3d.as_view(), name='product_rendering'),


	# paginacion alternativa no definitiva
	url(r'^auto/$', ProductListView.as_view()),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/socialhand/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import shop.urls
from search import views as search_views
from . import views, ocv
# from .views import notes
from django.views.generic import TemplateView



urlpatterns =  [
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include(shop.urls, namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'^search/', views.notes, name='search'),
    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL for social Auth
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^contact/$',views.contact, name='contact'),
    url(r'^api/',include('socialhand.api.urls',namespace='api')),
    #testing opencv tools into AR
    url(r'^face_detection/camera/$', ocv.camera),
    url(r'^silver_ar/$',views.three.as_view(), name='three'),
    url(r'^honeywell/$',views.Cascade.as_view(), name='cascade'),
    # testing object detect js
    url(r'^glasses/$',views.ben_frank.as_view(), name='ben_frank'),
    url(r'^g876_id0/$',views.ben_frank.as_view(), name='ben_frank'),

    #testing 360 look around  virtual tour with three.js
    url(r'^virtual/$', views.LookAround_360.as_view(), name = 'look_around' ),

     #testing babylon.js
    url(r'^virtual_test_kitchen/$', views.VirtualBabylon.as_view(), name = 'virtual_reality' ),
    url(r'^ar_cr3/$', views.Cr3ationAR.as_view(), name = 'AR_creation' ),
    url(r'^camaro/$', views.CamaroVirtual.as_view(), name = 'camaro' ),
    url(r'^warehouse_test/$', views.Warehouse.as_view(), name = 'warehouse' ),


]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = ('category')
		verbose_name_plural = ('categories')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
	author = models.ForeignKey('authtools.User', null=True)
	category = models.ForeignKey(Category,related_name='products')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField( upload_to='products/%Y-%m-%d',null=True,blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail',args=[self.id, self.slug])

	def save(self, *args, **kwargs):
            try:
                this = Product.objects.get(id=self.id)
                if this.image != self.image:
                    this.image.delete()
            except: pass
            super(Product, self).save(*args, **kwargs)

# function will be loaded only in Product3d class
def get_upload_path(instance, filename):
		""" apliying rsplit(condition,counter) :delete last elements from right to left
		and getting element by indexing selection []>>left to right  from ({././.},{.json})"""
		# Removing last slash from storage3d.URL: ("/media/models3d/<Date>","model_name.json")
		path_instance = instance.storage3d.url.rsplit('/',1)[0]
		""" apliying split(condition,counter) and removing firts elements from left to right
		and getting element by indexing selection [-1]>>right to left from ({././},{models3d/<Date>})"""
		# Removing first and second one slashes and getting last element
		path_dirname = path_instance.split('/',2)[-1]
		# join and build path to save model instance when function is loaded
		return '/'.join ([path_dirname, filename])


class Product3d(models.Model):
    mesh_selection = models.ForeignKey(Product, related_name='mesh', null=True)
    slug = models.CharField(max_length=200, db_index=True)
    name = models.CharField(max_length=200, db_index=True)
    storage3d = models.FileField(upload_to='models3d/%Y-%m-%d', null=True, blank=True)
    texture3d = models.ImageField(upload_to=get_upload_path, null=True, blank=True)
    custom_model_js = models.FileField(upload_to='models3d/each-js', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('shop:product_rendering', args=[self.id, self.slug])

    def __str__(self):
        return self.name



storage3d_upload_to = Product3d._meta.get_field('storage3d').upload_to
class Textures3d(models.Model):
    model3d = models.ForeignKey(Product3d)
    texture_3d = models.ImageField(upload_to=storage3d_upload_to,null=True,blank=True)


    def __str__(self):
        return self.name

src/shop/forms.py
from __future__ import unicode_literals
from django import forms
from .models import Product3d
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, Button, HTML, Row, Field, Fieldset

class Custom3dForm(forms.ModelForm):

    def __int__(self, *args, **kwargs):
        super(Custom3dForm,self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
            Field('custom_model_js'),
            # Submit('submit','Save Code', ccss_class='btn btn-success')
            # Submit('update', 'Update', css_class="btn-success"),
            Submit('update','Save Code',css_class="btn-success"),
            )

    class Meta:
        model = Product3d
        fields = ['custom_model_js','texture3d']

src/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product , Product3d, Textures3d
from .forms import Custom3dForm
from cart.forms import CartAddProductForm
from profiles.forms import ShopFor
from django.shortcuts import redirect
from profiles.views import ShowProfile
from profiles.models import Profile
from django.views.generic import TemplateView,View,DetailView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.list import ListView
from django.views.generic.base import ContextMixin
# para el-pagination
from el_pagination.views import AjaxListView
# import redis

# connect to redis
# r = redis.StrictRedis(host='localhost', port=6379, db=0)


def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	# products = Product.objects.filter(author=request.user).order_by('?')
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	return render(request,
				'shop/product/list.html',
				{'category'	: category,
				'categories': categories,
				'products': products})

def product_detail(request, id, slug):
	product = get_object_or_404(Product,
								id=id,
								slug=slug,
								available=True)
	# increment total image views by 1
	# total_views = r.incr('product:{}:views'.format(product.id))
	# increment image ranking by 1
	# r.zincrby('product_ranking', product.id, 1)
	cart_form = CartAddProductForm()
	img_related = product.name
	product3d = None
	if img_related :
	    try:
	        product3d = Product3d.objects.get(mesh_selection__name=img_related)
	    except Product3d.DoesNotExist:
	        product3d = None

	# looking author of product
	creator=product.author
	if creator :
		craftsman = get_object_or_404 (Profile,user_id=creator)
	return render(request,
				 'shop/product/detail.html',{
				 'product': product,
				 'product3d':product3d,
				 # 'total_views':total_views,
				 'cart_form': cart_form,
				 'craftsman':craftsman,})

def product_edit(request,id,slug):
        product = get_object_or_404(Product,
                                    id=id,
                                   	slug=slug)
        if request.method == "POST":
            form = ShopFor(request.POST,request.FILES or None, instance=product)
            if form.is_valid():
                product = form.save (commit=False)
                product.author = request.user
                product.save()
                return redirect("profiles:show_self")
        else:
            form = ShopFor (instance=product)
        return render(request, 'profiles/product_add.html', {'form':form})

def product_remove (request,id,slug):
		product = get_object_or_404(Product,
									id=id,
									slug=slug)
		user =request.user
		if product.author == user:
			product.delete()
		return redirect ('profiles:show_self')
#considerar otra vista para redirecionar en lugar de show_self

def product_ranking(request):
		# get image ranking dictionary
		product_ranking = r.zrange('product_ranking', 0, -1,desc=True)[:10]
		product_ranking_ids = [int(id) for id in product_ranking]
		# get most viewed images
		most_viewed = list(Product.objects.filter(id__in=product_ranking_ids))
		most_viewed.sort(key=lambda x: product_ranking_ids.index(x.id))
		return render(request,
					'shop/product/ranking.html',
					{'section': 'products',
					'most_viewed': most_viewed})


class Rendering3d(TemplateView):
	template_name = 'shop/product/product_rendering.html'
	http_method_names = ['post','get']

	def get(self, request,*args,**kwargs):
		id_product = self.kwargs.get('id')
		slug = self.kwargs.get('slug')
		product3d = get_object_or_404(Product3d,
									  id=id_product,
						 			  slug=slug)

		texture_maps = Textures3d.objects.filter(model3d=product3d)
		form = Custom3dForm
		asignament = product3d.slug
		if request.method == 'POST':
			form = Custom3dForm(request.POST,
								request.FILES,
								instance=product3d)
			kwargs['form'] = form
			if form.is_valid():
				product3d = form.save(commit=False)
				product3d.save()
		else:
			form = Custom3dForm(instance=product3d)
		kwargs['product3d'] = product3d
		kwargs['form'] = form
		kwargs['textures3d'] =  texture_maps
		return super(Rendering3d,self).get(request,*args,**kwargs)


# def product_rendering(request,id,slug):
#     product3d = get_object_or_404 (Product3d,id=id,slug=slug)
#     if request.method == "POST":
#         form = Custom3dForm(request.POST,
#                             request.FILES,
#                             instance= product3d)
#         if form.is_valid():
#             product3d = form.save(commit=False)
#             product3d.save()
#     else:
#         form = Custom3dForm(instance=product3d)
#     return render(request, 'shop/product/product_rendering.html',
#                     {'product3d':product3d, 'form':form})

class ProductListView(AjaxListView):
		context_object_name= 'products'
		template_name = "shop/product/list.html"
		page_template = "shop/product_list.html"

		def get_queryset(self):
			return Product.objects.all()

		def get_context_data(self,**kwargs):
			category = None
			slug = self.kwargs.get('slug')
			products = Product.objects.all()
			categories = Category.objects.all()
			kwargs['categories']= categories
			if  slug:
				category = get_object_or_404(Category, slug=slug)
				products =products.filter(category=category)
			kwargs['products'] = products
			kwargs['category'] = category
			return super(ProductListView,self).get_context_data(**kwargs)

src/shop/templates/shop/product/detail.html
{% extends "shop/home.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
	{% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}


{% block container %}
<br><br>
<div class="container-fluid">
    <div class="no-padding">
        <div class=" col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div id="detail"class="justified-gallery" style="background-color: white; margin-top:10px;">
            	<div>
            		<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "image/noimage.png" %}{% endif %}"  alt="<h3 class='text-center'>{{product.name}} </br>${{ product.price }}</h3>">
            	</div>
            </div>
        </div>

         {% if product3d %}
	         <div class=" col-xs-12 col-sm-12 col-md-6 col-lg-6" style="background-color: black; margin-top:10px;">
	        	<iframe id="fast_3d_view" scrolling="no" frameborder="0" height="370vh" width="100%" src="{% url 'shop:product_rendering' product3d.id product3d.slug %}" style="margin-top:20px; padding: 0;">
				</iframe>

				<a class=" text-center btn btn-secondary btn-large"  href="{% url 'shop:product_rendering' product3d.id product3d.slug %}" style="display: inline-block;" >Full 3d View&nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-eye-open" style='color:white; display:inline-block;'>&nbsp;</span></a>
			</div>

		{% endif %}


    </br>
    <div class=" col-xs-12 col-sm-12 col-md-6 col-lg-6 col-md-offset-0">
    	 {% if product.author == user %}
    	 <div class="col-md-4" style="float: left;">
    	 	<a class="btn btn-primary"  href="{% url 'shop:product_edit' product.id product.slug %}"><span class="glyphicon glyphicon-pencil"></span></a>
    	 	<!-- first -->
    	 	<button type="button" class="btn btn-primary" data-toggle="popover"  data-trigger="focus" data-placement="auto" data-content="<div class='lead text-center'>
    	 	{% trans 'Are you sure you want to delete this file?'%}</div>
    	 	<div class='text-center'>
    	 	<a class='btn btn-primary btn-lg' href='{% url 'shop:product_remove' product.id product.slug %}'>
    	 	<span class='glyphicon glyphicon-ok'></span>
    	 	</a>
    	 	<a class='btn btn-danger btn-lg' style='margin:15px;' onclick='$(this).parent().hide();'>
    	 	<span class='glyphicon glyphicon-remove'></span>
    	 	</a>
    	 	</div>">
        	<span class="glyphicon glyphicon-trash"></span></button>
    	 </div>

    	 <!--implementing counter views with redis /not available in  PA-->
    	<!--<div class=" text-right col-md-4 col-md-offset-4" style="float: right;">-->
    	<!--  <span class="count">-->
    	<!--	<span class="total">{{ total_views }}</span>-->
    	<!--	{% trans 'View'%}{{ total_views|pluralize }}-->
    	<!--  </span>-->
    	<!--</div>-->
    	 </br></br>
    	 {% endif %}
    	<div class="col-md-offset-6">
    	  <form class="form-inline" style="float: right;" action="{% url 'cart:cart_add' product.id%}" method="post">
    		<div class="form-group  ">
    			{% crispy cart_form %}
    			{% csrf_token %}
    		</div>
    	  </form>
    	</div>
    </div>
    </div>
</div>


<div class="container-fluid">
    <hr class="custom">

  <!--   <div class="container-fluid">-->
		<!--{% if product3d %}-->
		<!--{{product3d.name}} |-->
		<!--{{product3d.slug}}-->
		<!-- |-->
		<!-- {{product3d.id}}-->
		<!--{{product3d.storage3d}}-->
		<!--	<a class="btn btn-secondary btn-large"  href="{% url 'shop:product_rendering' product3d.id product3d.slug %}"><span class="glyphicon glyphicon-eye-open"></span></a>-->
		<!--{% endif %}-->
  <!--  </div>-->



  <div id="author-accordion">
	<div class="no-padding panel-group" id="accordion">
	  <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 ">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
		      <h4 class="lead panel-title text-center"> {% trans 'Handcrafted by:'%}{{craftsman.get_full_name }}
		      </h4>
		    </a>
		  </div>
		  <div id="collapse1" class="panel-collapse collapse">
		    <div class="panel-body text-center">
		      <h3 style="font-family:Lobster;" ><font color="black">{{craftsman.get_short_name }}</font></h3>
		      	<img data-toggle="popover"  data-placement="auto bottom" data-content=" <blockquote class='lead' >{% if craftsman.bio%}{{ craftsman.bio }}{% else%}{% trans 'I invite you to see my profile '%}{% endif %}</blockquote> " title=" <h4><a href='{% url 'profiles:show' craftsman.slug %}'>{{craftsman.get_short_name }}</a></h4>" class="img-circle img-responsive img-thumbnail" src="{% thumbnail craftsman.picture|default:'default_profile.png' 150x150 crop %}">
		    </div>
		  </div>
		</div>
	  </div>
	</div>
  </div>

  <div id="description-accordion">
 	<div class="no-padding panel-group center-block" id="accordion" >
	  <div class=" col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-1">
	    <div class=" panel panel-default">
	      <div class="panel-heading">
	        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
	          <h4 class="panel-title text-center">
	          {% trans 'Description:'%}
	          </h4>
	        </a>
	   	  </div>
	      <div id="collapse2" class="collapse collapse">
	      	<div class="panel-body">
	      	  <h3  style="font-family:Lobster;" ><font color="black">{{ product.name }}</font></h3>
	      		<p class="lead">{{product.description}}</p>
	      	</div>
	      </div>
	 	</div>
	  </div>
  	</div>
  </div>
</div>


{% endblock container %}


{% block scripts %}
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script src = "{%static 'site/js/jquery.justifiedGallery.js' %}"></script>
<script>
    $("#detail").justifiedGallery({
    rowHeight : 400,
    maxRowHeight : 350,
    lastRow : 'nojustify',
    // nojustify or hide for last image
    margins : 10
    });
</script>
<script>
	$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
	});
</script>
<script>
	$("[data-toggle=popover]")
	.popover({html:true})
</script>
 <script>
  $('.popover-markup>.trigger').popover({
    html: true,
    title: function () {
        return $(this).parent().find('.head').html();
    },
    content: function () {
        return $(this).parent().find('.content').html();
    }
});
  </script>
<script>
	function close_please() {
    $('#meddelanden').popover('hide');
}
</script>
<script >
// How to hide content from iframe tag
$(function(){
			var Iframecontent=$('#fast_3d_view')
			Iframecontent.load(function(){
				Iframecontent.contents().find('.navbar-transparent').hide();
			})
		})
</script>


{% endblock scripts %}

src/shop/templates/shop/product/list.html
{% extends "shop/home.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load el_pagination_tags %}

{% block title %}
		{% if category %}
			{{ block.super }}{{ category.name }}
		{% else %}
			{{ block.super }} {% trans 'Products' %}
		{% endif %}
{% endblock %}

	{% block content %}

        <div class="container-fluid">
            <div class="col-lg-12">
                <h4 class="text-center">
                    {% trans 'Handcrafted things' %}
                </h4>
            </div>
        </div>
<!-- {% for product  in products %}
  {% if product.category == category %}
    -{{ product.name }}.
    {{ product.category }}-
    {%else %}
    {%if not category %}
         /{{ product.name }}.
            {{ product.category }}/
            {% endif%}
    {% endif%}
{% endfor %} -->

<div id="categories" class="container-fluid">
    <div class="btn-group btn-group-lg dropdown-menu">
    <button  class="btn-default btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if category.name %}{{ category.name }}{% else %}{% trans 'Categories'%}{% endif %}<span class="caret "></span></button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}" class=" ">{% trans 'All' %}</a>
            </li>
            <li class="divider"></li>
        {% for category in categories %}
            <li {% if category.slug == category.slug %}{% endif %}>
                <a tabindex="-1" href="{{ category.get_absolute_url }}" class="product-category">{{ category.name }}</a>
            </li>
        {% endfor %}
            <!-- <li class="divider"></li>
            <li><a tabindex="-1" href="#">Other</a></li> -->
        </ul>
    </div>
 </div>

<div id="pagination" class="endless_page_template">
        {% include "shop/product_list.html" %}
</div>

{% endblock  %}


{% block scripts %}
<script src="{% static 'site/js/jquery.js' %}" ></script>
<script src="{% static 'site/js/el-pagination.js' %}"></script>
<script src="{% static 'site/js/el-pagination-endless.js' %}"></script>
<script>$.endlessPaginate({
            paginateOnScroll: true,
            // margin for scroll in pixels
            paginateOnScrollMargin: 120,
        });
</script>
<script >$(function(){
  $(".dropdown-menu li a").click(function(){
    $(".btn:first-child").text($(this).text());
     $(".btn:first-child").val($(this).text());
  });});
</script>

{% endblock scripts %}

src/shop/templates/shop/product/ranking.html
{% extends "shop/home.html" %}
{% load staticfiles %}
{% load thumbnail %}



{% block title %}Product ranking{% endblock %}

{% block content %}
	<h2>Product ranking</h2>
	<ol>
	{% for product in most_viewed %}
		<li>
		<a href="{{ product.get_absolute_url }}">
		{{ product.name }}
		</a>
		</li>
	{% endfor %}
	</ol>
{% endblock %}