src/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),

]

src/shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import  ProductListView

urlpatterns = [

	url(r'^productos/$', ProductListView.as_view(), name='product_list'),
	url(r'^productos/(?P<slug>[-\w]+)/$',ProductListView.as_view(),name='product_list_by_category'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/edit/$', views.product_edit, name='product_edit'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/remove/$',views.product_remove, name='product_remove'),
	url(r'^ranking/$', views.product_ranking, name='create'),

    #render 3d model for custom code for each model
	url(r'^productos/render/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.Rendering3d.as_view(), name='product_rendering'),


	# paginacion alternativa no definitiva
	url(r'^auto/$', ProductListView.as_view()),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/socialhand/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import shop.urls
from search import views as search_views
from . import views, ocv
# from .views import notes
from django.views.generic import TemplateView



urlpatterns =  [
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include(shop.urls, namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'^search/', views.notes, name='search'),
    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL for social Auth
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^contact/$',views.contact, name='contact'),
    url(r'^api/',include('socialhand.api.urls',namespace='api')),
    #testing opencv tools into AR
    url(r'^face_detection/camera/$', ocv.camera),
    url(r'^silver_ar/$',views.three.as_view(), name='three'),
    url(r'^honeywell/$',views.Cascade.as_view(), name='cascade'),
    # testing object detect js
    url(r'^glasses/$',views.ben_frank.as_view(), name='ben_frank'),
    url(r'^g876_id0/$',views.ben_frank.as_view(), name='ben_frank'),

    #testing 360 look around  virtual tour with three.js
    url(r'^virtual/$', views.LookAround_360.as_view(), name = 'look_around' ),

     #testing babylon.js
    url(r'^virtual_test_kitchen/$', views.VirtualBabylon.as_view(), name = 'virtual_reality' ),
    url(r'^ar_cr3/$', views.Cr3ationAR.as_view(), name = 'AR_creation' ),
    url(r'^camaro/$', views.CamaroVirtual.as_view(), name = 'camaro' ),
    url(r'^warehouse_test/$', views.Warehouse.as_view(), name = 'warehouse' ),


]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = ('category')
		verbose_name_plural = ('categories')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
	author = models.ForeignKey('authtools.User', null=True)
	category = models.ForeignKey(Category,related_name='products')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField( upload_to='products/%Y-%m-%d',null=True,blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail',args=[self.id, self.slug])

	def save(self, *args, **kwargs):
            try:
                this = Product.objects.get(id=self.id)
                if this.image != self.image:
                    this.image.delete()
            except: pass
            super(Product, self).save(*args, **kwargs)

# function will be loaded only in Product3d class
def get_upload_path(instance, filename):
		""" apliying rsplit(condition,counter) :delete last elements from right to left
		and getting element by indexing selection []>>left to right  from ({././.},{.json})"""
		# Removing last slash from storage3d.URL: ("/media/models3d/<Date>","model_name.json")
		path_instance = instance.storage3d.url.rsplit('/',1)[0]
		""" apliying split(condition,counter) and removing firts elements from left to right
		and getting element by indexing selection [-1]>>right to left from ({././},{models3d/<Date>})"""
		# Removing first and second one slashes and getting last element
		path_dirname = path_instance.split('/',2)[-1]
		# join and build path to save model instance when function is loaded
		return '/'.join ([path_dirname, filename])


class Product3d(models.Model):
    mesh_selection = models.ForeignKey(Product, related_name='mesh', null=True)
    slug = models.CharField(max_length=200, db_index=True)
    name = models.CharField(max_length=200, db_index=True)
    storage3d = models.FileField(upload_to='models3d/%Y-%m-%d', null=True, blank=True)
    texture3d = models.ImageField(upload_to=get_upload_path, null=True, blank=True)
    custom_model_js = models.FileField(upload_to='models3d/each-js', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('shop:product_rendering', args=[self.id, self.slug])

    def __str__(self):
        return self.name



storage3d_upload_to = Product3d._meta.get_field('storage3d').upload_to
class Textures3d(models.Model):
    model3d = models.ForeignKey(Product3d)
    texture_3d = models.ImageField(upload_to=storage3d_upload_to,null=True,blank=True)


    def __str__(self):
        return self.name

src/shop/forms.py
from __future__ import unicode_literals
from django import forms
from .models import Product3d
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, Button, HTML, Row, Field, Fieldset

class Custom3dForm(forms.ModelForm):

    def __int__(self, *args, **kwargs):
        super(Custom3dForm,self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
            Field('custom_model_js'),
            # Submit('submit','Save Code', ccss_class='btn btn-success')
            # Submit('update', 'Update', css_class="btn-success"),
            Submit('update','Save Code',css_class="btn-success"),
            )

    class Meta:
        model = Product3d
        fields = ['custom_model_js','texture3d']

src/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product , Product3d, Textures3d
from .forms import Custom3dForm
from cart.forms import CartAddProductForm
from profiles.forms import ShopFor
from django.shortcuts import redirect
from profiles.views import ShowProfile
from profiles.models import Profile
from django.views.generic import TemplateView,View,DetailView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.list import ListView
from django.views.generic.base import ContextMixin
# para el-pagination
from el_pagination.views import AjaxListView
# import redis

# connect to redis
# r = redis.StrictRedis(host='localhost', port=6379, db=0)


def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	# products = Product.objects.filter(author=request.user).order_by('?')
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	return render(request,
				'shop/product/list.html',
				{'category'	: category,
				'categories': categories,
				'products': products})

def product_detail(request, id, slug):
	product = get_object_or_404(Product,
								id=id,
								slug=slug,
								available=True)
	# increment total image views by 1
	# total_views = r.incr('product:{}:views'.format(product.id))
	# increment image ranking by 1
	# r.zincrby('product_ranking', product.id, 1)
	cart_form = CartAddProductForm()
	img_related = product.name
	product3d = None
	if img_related :
	    try:
	        product3d = Product3d.objects.get(mesh_selection__name=img_related)
	    except Product3d.DoesNotExist:
	        product3d = None

	# looking author of product
	creator=product.author
	if creator :
		craftsman = get_object_or_404 (Profile,user_id=creator)
	return render(request,
				 'shop/product/detail.html',{
				 'product': product,
				 'product3d':product3d,
				 # 'total_views':total_views,
				 'cart_form': cart_form,
				 'craftsman':craftsman,})

def product_edit(request,id,slug):
        product = get_object_or_404(Product,
                                    id=id,
                                   	slug=slug)
        if request.method == "POST":
            form = ShopFor(request.POST,request.FILES or None, instance=product)
            if form.is_valid():
                product = form.save (commit=False)
                product.author = request.user
                product.save()
                return redirect("profiles:show_self")
        else:
            form = ShopFor (instance=product)
        return render(request, 'profiles/product_add.html', {'form':form})

def product_remove (request,id,slug):
		product = get_object_or_404(Product,
									id=id,
									slug=slug)
		user =request.user
		if product.author == user:
			product.delete()
		return redirect ('profiles:show_self')
#considerar otra vista para redirecionar en lugar de show_self

def product_ranking(request):
		# get image ranking dictionary
		product_ranking = r.zrange('product_ranking', 0, -1,desc=True)[:10]
		product_ranking_ids = [int(id) for id in product_ranking]
		# get most viewed images
		most_viewed = list(Product.objects.filter(id__in=product_ranking_ids))
		most_viewed.sort(key=lambda x: product_ranking_ids.index(x.id))
		return render(request,
					'shop/product/ranking.html',
					{'section': 'products',
					'most_viewed': most_viewed})


class Rendering3d(TemplateView):
	template_name = 'shop/product/product_rendering.html'
	http_method_names = ['post','get']

	def get(self, request,*args,**kwargs):
		id_product = self.kwargs.get('id')
		slug = self.kwargs.get('slug')
		product3d = get_object_or_404(Product3d,
									  id=id_product,
						 			  slug=slug)

		texture_maps = Textures3d.objects.filter(model3d=product3d)
		form = Custom3dForm
		asignament = product3d.slug
		if request.method == 'POST':
			form = Custom3dForm(request.POST,
								request.FILES,
								instance=product3d)
			kwargs['form'] = form
			if form.is_valid():
				product3d = form.save(commit=False)
				product3d.save()
		else:
			form = Custom3dForm(instance=product3d)
		kwargs['product3d'] = product3d
		kwargs['form'] = form
		kwargs['textures3d'] =  texture_maps
		return super(Rendering3d,self).get(request,*args,**kwargs)


# def product_rendering(request,id,slug):
#     product3d = get_object_or_404 (Product3d,id=id,slug=slug)
#     if request.method == "POST":
#         form = Custom3dForm(request.POST,
#                             request.FILES,
#                             instance= product3d)
#         if form.is_valid():
#             product3d = form.save(commit=False)
#             product3d.save()
#     else:
#         form = Custom3dForm(instance=product3d)
#     return render(request, 'shop/product/product_rendering.html',
#                     {'product3d':product3d, 'form':form})

class ProductListView(AjaxListView):
		context_object_name= 'products'
		template_name = "shop/product/list.html"
		page_template = "shop/product_list.html"

		def get_queryset(self):
			return Product.objects.all()

		def get_context_data(self,**kwargs):
			category = None
			slug = self.kwargs.get('slug')
			products = Product.objects.all()
			categories = Category.objects.all()
			kwargs['categories']= categories
			if  slug:
				category = get_object_or_404(Category, slug=slug)
				products =products.filter(category=category)
			kwargs['products'] = products
			kwargs['category'] = category
			return super(ProductListView,self).get_context_data(**kwargs)

src/shop/templates/shop/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n%}

 


{% block title %}{{ block.super }}{% endblock %}



<!-- code for the shop -->
<link href="{% static 'site/css/main.css' %}" rel="stylesheet">

{% block container %}	

<div id="header">
	<!-- <p class="text-center ">{% trans 'Gallery' %}</p>	 -->
</div>
<div id="subheader">
	<div class="cart">
		{% with total_items=cart|length %}
		<span class="glyphicon glyphicon-shopping-cart"></span>
			{% if cart|length > 0 %}
			{% trans 'Your choices:' %}			
				<a href="{% url "cart:cart_detail" %}">
					{{ total_items }} artículo{{ total_items|pluralize }},
					${{ cart.get_total_price }}
				</a>
			{% else %}
			{% trans 'Your cart is empty'%}
			:(
			{% endif %}
		{% endwith %}
	</div>
</div>
		<div>
			{% block content %}
			{% endblock %}
		</div>


{% endblock %}
{% block scripts %}
{% endblock scripts %}

src/shop/templates/shop/product_list.html
{% load static %}
{% load el_pagination_tags %}
{% load thumbnail %}

{% paginate products %}
<div  id="b" class="justified-gallery" style="background-color: black;" >
  {% for product  in products %}
      {% if product.category == category %}
        <a href="{{ product.get_absolute_url }}"class="portfolio-box  image-frame">
          <img  src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'image/noimage.png' %}{% endif %}">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                <h3>{{ product.name }}</h3>
                </div>
                <div class="project-name">
                <h3>By: {{ product.author.get_short_name }}</h3>
                </div>
                <div>{{ product.category }}</div>
              </div>
          </div>
        </a>
      {% else %}
      {% if not category %}
          <a href="{{ product.get_absolute_url }}"class="portfolio-box  image-frame">
             <img title="profile picture" src="{% if product.image %}{% thumbnail product.image 650x650 crop %}{%else %}{% static 'image/noimage.png' %}{% endif %}">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                  <h3>{{ product.name }}</h3>
                  </div>
                  <div class="project-name">
                  </div>
                  <div>By: {{ product.author.get_short_name }}</div>
                </div>
             </div>
          </a>
      {% endif %}
      {% endif %}
  {% endfor %}
</div>

{% show_more %}

{% block scripts %}
<script  src="{% static 'site/js/jquery.js' %}" ></script>
<script src="{% static 'site/js/el-pagination.js' %}"></script>
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script src = "{%static 'site/js/jquery.justifiedGallery.js' %}"></script>
<script>$.endlessPaginate({paginateOnScroll: true});</script>
<script>
    $(function(){
    var i=0;
    $('.justified-gallery').each(function(){
        var temp='b'+i;
        $(this).attr('id',temp);
        ++i;
        console.log($(this).attr('id'));
    });
  });
</script>
<script>
     $("#b").justifiedGallery({
    rowHeight : 230,
    maxRowHeight : 150,
    cssAnimation : true,
    lastRow : 'justify',
    // nojustify or hide for last image
    margins : 15,
    border : 8,

    });
</script>

<script >
// add color random in gallery images
  var back = ["#DF01D7","#8E44AD","#AEA8D3","#F62459","#DB0A5B","#D64541","#D2527F","#522770","#61AEFF","#EBABD6","#543BC4","#ff21e9","#F88400","#FFDA00","#BF4B9C"];
  $('.portfolio-box-caption').each(function() {
    // First random color
    var rand1 = back[Math.floor(Math.random() * back.length)];
    // Second random color
    var rand2 = back[Math.floor(Math.random() * back.length)];
    var grad = $(this);
    // Convert Hex color to RGB
    function convertHex(hex,opacity){
        hex = hex.replace('#','');
        r = parseInt(hex.substring(0,2), 16);
        g = parseInt(hex.substring(2,4), 16);
        b = parseInt(hex.substring(4,6), 16);
      // Add Opacity to RGB to obtain RGBA
        result = 'rgba('+r+','+g+','+b+','+opacity/50+')';
        return result;
    }
    // Gradient rules
    grad.css('background-color', convertHex(rand1,40) );
    grad.css("filter", "progid:DXImageTransform.Microsoft.gradient( startColorstr='"+ convertHex(rand1,40) +"', endColorstr='"+ convertHex(rand2,40) +"',GradientType=0 )");
  })
</script>
{% endblock scripts %}