src/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),

]

src/socialhand/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import shop.urls
from search import views as search_views
from . import views, ocv
# from .views import notes
from django.views.generic import TemplateView



urlpatterns =  [
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include(shop.urls, namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'^search/', views.notes, name='search'),
    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL for social Auth
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^contact/$',views.contact, name='contact'),
    url(r'^api/',include('socialhand.api.urls',namespace='api')),
    #testing opencv tools into AR
    url(r'^face_detection/camera/$', ocv.camera),
    url(r'^silver_ar/$',views.three.as_view(), name='three'),
    url(r'^honeywell/$',views.Cascade.as_view(), name='cascade'),
    # testing object detect js
    url(r'^glasses/$',views.ben_frank.as_view(), name='ben_frank'),
    url(r'^g876_id0/$',views.ben_frank.as_view(), name='ben_frank'),

    #testing 360 look around  virtual tour with three.js
    url(r'^virtual/$', views.LookAround_360.as_view(), name = 'look_around' ),

     #testing babylon.js
    url(r'^virtual_test_kitchen/$', views.VirtualBabylon.as_view(), name = 'virtual_reality' ),
    url(r'^ar_cr3/$', views.Cr3ationAR.as_view(), name = 'AR_creation' ),
    url(r'^camaro/$', views.CamaroVirtual.as_view(), name = 'camaro' ),
    url(r'^warehouse_test/$', views.Warehouse.as_view(), name = 'warehouse' ),


]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/cart/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field

 
 
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 40)]
class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(
								choices=PRODUCT_QUANTITY_CHOICES,
								coerce=int,
								label='')
	update = forms.BooleanField(required=False,
								initial=False,
								widget=forms.HiddenInput) 
	def __init__ (self,*args, **kwargs):
		super (CartAddProductForm,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.form_tag = False
		self.helper.layout = Layout (
			Field ('quantity'),
			Field ('update'),
			Submit('update', 'Add to cart', css_class='btn-success')

			)

src/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
 

@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product,
				quantity=cd['quantity'],
				update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(
						initial={'quantity': item['quantity'],
						'update': True})
	return render(request, 'cart/detail.html', {'cart': cart}) 

src/cart/templates/cart/detail.html
{% extends "shop/home.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
	Tu carrito de compras 
{% endblock %}

{% block container %}
<h1>Tus elecciones!</h1>
<table class="cart">
	<thead>
	
	<tbody>
	<tr class="head-and-footer">
		<th class="lead text-center">{% trans 'Product'%}</th>
		<th class="lead text-center">{% trans 'Description'%}</th>
		<th class="lead text-center">{% trans 'Quantity'%}</th>
		<th class="lead text-center">{% trans 'Clear ' %} </th>
		<th class="lead text-center">{% trans 'Unit Price'%}</th>
		<th class="lead text-center">{% trans 'Your account'%}</th>
	</tr>
	 {% for item in cart %}
		{% with product=item.product %}
		<tr class="table-content">
			<td class="text-center">
				<a href="{{ product.get_absolute_url }}">
					<img class="img-square img-thumbnail" src="{% if product.image %}{{ product.image.url}}{% else %}{% static 'image/noimage.png' %}{% endif %}">
				</a>
			</td>
			<td class="lead text-center">{{ product.name }}</td>
			<td>
				<div class="container-fluid">
				<form  class="text-center" action="{% url 'cart:cart_add' product.id%}" method="post">
				 {{ item.update_quantity_form.quantity }}
				{{ item.update_quantity_form.update }} 
				&nbsp;&nbsp;<a onclick="$(this).closest('form').submit()"><span class="glyphicon glyphicon-refresh" style="font-size: 2em;"></span></a>
				{% csrf_token %}
				</form></div>
			</td>
			<td class="lead text-center">
				<a href="{% url 'cart:cart_remove' product.id%}">
					<span class="glyphicon glyphicon-trash" style="font-size: 1.5em;">
					</span></a>
			</td>
			<td class="lead text-center">
			${{ item.price }}
			</td>
			<td class="lead text-center">
			${{ item.total_price }}
			</td>
		</tr>
		{% endwith %}
	 {% endfor %}
	 <tr class="head-and-footer">
	 	<td colspan="4"></td>
		<td class="lead text-center">
		{% trans 'Total'%}</td>
		<td class="lead text-center">
		${{ cart.get_total_price }}</td>
	 </tr>
	</tbody>
			</table>
		<p class="text-right">
			
			<a href="{% url "shop:product_list" %}">
				<button type="button" class="btn btn-warning">{% trans 'Continue Shopping'%}</button>
			</a>
			<a href="{% url "orders:order_create" %}">
		    	<button class="btn btn-success" style="padding-left: 45px; padding-right:45px;">{% trans 'Checkout' %}</button>
		    </a>
		  
		</p>
		</br></br></br></br></br>
{% endblock container  %}